//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeSupply.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDiscountService")]
    public interface IDiscountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountService/GetDiscount", ReplyAction="http://tempuri.org/IDiscountService/GetDiscountResponse")]
        double GetDiscount(string discountCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscountService/GetDiscount", ReplyAction="http://tempuri.org/IDiscountService/GetDiscountResponse")]
        System.Threading.Tasks.Task<double> GetDiscountAsync(string discountCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiscountServiceChannel : OfficeSupply.ServiceReference1.IDiscountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiscountServiceClient : System.ServiceModel.ClientBase<OfficeSupply.ServiceReference1.IDiscountService>, OfficeSupply.ServiceReference1.IDiscountService {
        
        public DiscountServiceClient() {
        }
        
        public DiscountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiscountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetDiscount(string discountCode) {
            return base.Channel.GetDiscount(discountCode);
        }
        
        public System.Threading.Tasks.Task<double> GetDiscountAsync(string discountCode) {
            return base.Channel.GetDiscountAsync(discountCode);
        }
    }
}
